### ISSUE TITLE
Trailers mode doesn't seem to be working

### ISSUE THREAD

**Issue by AndrewMayorov** [tpeczek/Lib.AspNetCore.ServerTiming#11]
Trying now with aspnetcore 5 and latest Chrome. Trailers are supported, but not used by the library. 

Most likely it happens because check for `NETCOREAPP3_0` became non sufficient. 

Also I noticed that you use your own `AllowsTrailers` extension method, which analyzes "TE" header, which is not present in the headers collection. But I see that there is standard `RequestTrailerExtensions.SupportsTrailers` method available, so I suppose it's better to switch.

**Comment by tpeczek** [comment]
Great catch with that compilation constant. Indeed I've messed up greatly when adding support for .NET 5 and it broke this feature. The fix is already on NuGet.

Now about those checks. The code in fact performs both.

```
if (context.Request.AllowsTrailers() && context.Response.SupportsTrailers())
{
    await HandleServerTimingAsTrailerHeaderAsync(context, serverTiming);
}
else
{
    await HandleServerTimingAsResponseHeaderAsync(context, serverTiming);
}
```
And they are both needed. The `RequestTrailerExtensions.SupportsTrailers` provides information if ASP.NET Core supports trailers for current request on technical level (in general ASP.NET Core supports trailers only for HTTP/2), while the check for `TE` header is required by HTTP (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer).

> The TE request header needs to be set to "trailers" to allow trailer fields.

The browser which does that correctly is FireFox.

![image](https://user-images.githubusercontent.com/1446301/119869471-908dc180-bf20-11eb-90da-34e07518de60.png)

**Comment by AndrewMayorov** [comment]
Thanks for the explanation about trailers, Tomasz! Never used them, and somehow assumed that regular Chrome already supports it. :)

**Comment by tpeczek** [comment]
You're welcome :).
