### ISSUE TITLE
Error when description contains non-english chars

### ISSUE THREAD

**Issue by CheloXL** [tpeczek/Lib.AspNetCore.ServerTiming#2]
Nor sure if this should be handled by you, but if I try to send the following header `new ServerTimingMetric("Execution-Time", stopwatch.ElapsedMilliseconds, "Tiempo de ejecución")` it fails with an exception from kestrel saying that there is an invalid char in the headers. Changing the 'ó' by 'o' fixes the issue.

Maybe both the name and the description needs to be encoded somehow?

**Comment by tpeczek** [comment]
The error would be correct if it would be coming from *name* property because it is defined as *token* in [standard](http://www.w3.org/TR/server-timing/#dfn-server-timing-header-field), where *token* is defined as follows in [RFC 7230](https://tools.ietf.org/html/rfc7230):

> token          = 1\*tchar
> tchar           = "!" / "#" / "$" / "%" / "&" / "'" / "*"
>                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
>                    / DIGIT / ALPHA
>                    ; any VCHAR, except delimiters

(where *VCHAR* is an US-ASCII visual character).

But *description* can be a *quoted-string* (and this implementation uses this possibility) which should allow wider set of characters:

> quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
> qdtext              = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text
> obs-text       = %x80-FF

The limitation is currently by design in Kestrel (see aspnet/KestrelHttpServer#1076) and the team is planning on parametrizing this behaviour for request (see aspnet/KestrelHttpServer#1144) - I will add a question there regarding responses.

In general at this point I'm unable to do anything about it. You can add your own encoding (for example Base64) but if you want to benefit from Chrome displaying those values for you it will not be able to understand it.

**Comment by CheloXL** [comment]
Thanks!
